"""prima migrazione

Revision ID: 95c6d9205f17
Revises: 
Create Date: 2025-09-24 18:55:06.061912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c6d9205f17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bidone',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.String(length=15), nullable=True),
    sa.Column('distance', sa.String(length=15), nullable=True),
    sa.Column('is_full', sa.Boolean(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('fulness', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('citta', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inserviente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('citta', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inserviente')
    op.drop_table('bidone')
    # ### end Alembic commands ###
