"""Create Inserviente

Revision ID: d2de109171c5
Revises: 
Create Date: 2025-03-28 13:40:20.466370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2de109171c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utente')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utente',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=True),
    sa.Column('cognome', sa.VARCHAR(length=100), nullable=True),
    sa.Column('UUID', sa.VARCHAR(length=36), nullable=True),
    sa.Column('password', sa.VARCHAR(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
